name: Releases

on:
  push:
    branches: [main]

jobs:
  releases:
    name: profile apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.0.3
      - run: flutter pub get
      - run: flutter build apk --profile
